apiVersion: v1
kind: ResourceQuota
metadata:
  name: executor-quota
  namespace: executor
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: "2Gi"
    limits.cpu: "8"
    limits.memory: "4Gi"

